server:
  host     : localhost
  port     : 1337
  type     : production
  timezone : Europe/Ireland

log:
  request : false
  response: false

deploy:
  - git pull
  - npm install
  - grunt
  - pm2 restart NOMADCODE
